queries:
  issueByCategory:
    query: SELECT * FROM Issues WHERE Category = $Category
requests:
  totalIssueCount:
    query: SELECT COUNT(*) FROM Issues
    type: Scalar
  redundanciesInCode:
    queryRef: issueByCategory
    type: Collection
    parameters:
      Category: Redundancies in Code
  topIssue:
    query: SELECT * FROM Issues LIMIT (1)
    type: Object
  issueCountByCategory:
    query: SELECT Category, COUNT(*) AS IssueCount FROM Issues GROUP BY Category
    type: Collection

